In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Read the csv file into a pandas DataFrame
X = pd.read_csv('Training sheet.csv')
X.head()

id                                           name  \
0    7950115                                         Avatar   
1   50950115  Harry Potter and the Deathly Hallows: Part II   
2  119870115                                 Transformers 3   
3  119590115                                    Toy Story 3   
4   91700115                     Pirates of the Caribbean 4   

                                    display_name  production_year  \
0                                         Avatar             2009   
1  Harry Potter and the Deathly Hallows: Part II             2011   
2                 Transformers: Dark of the Moon             2011   
3                                    Toy Story 3             2010   
4    Pirates of the Caribbean: On Stranger Tides             2011   

   movie_sequel    creative_type                             source  \
0             0  Science Fiction                Original Screenplay   
1             1          Fantasy  Based on Fiction Book/Short Story   
2             1  Science Fiction                        Based on TV   
3             1     Kids Fiction                Original Screenplay   
4             1          Fantasy           Based on Theme Park Ride   

       production_method      genre language  \
0  Animation/Live Action     Action  English   
1  Animation/Live Action  Adventure  English   
2  Animation/Live Action     Action  English   
3      Digital Animation  Adventure  English   
4            Live Action  Adventure  English   

                                 board_rating_reason  \
0  For intense epic battle sequences and warfare,...   
1  for some sequences of intense action violence ...   
2  for intense prolonged sequences of sci-fi acti...   
3                                            General   
4  for intense sequences of action/adventure viol...   

  movie_board_rating_display_name movie_release_pattern_display_name  total  \
0                           PG-13                               Wide   2784   
1                           PG-13                               Wide   1328   
2                           PG-13                               Wide   1124   
3                               G                               Wide   1064   
4                           PG-13                               Wide   1044   

   Category  
0         9  
1         9  
2         9  
3         9  
4         9

In [3]:
# Import necessary libraries and packages

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import SGD
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import tree
from sklearn import linear_model
from sklearn.model_selection import KFold
#from sklearn.cross_validation import StratifiedKFold
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn import metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, explained_variance_score, r2_score
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

C:\Users\dinot\AppData\Local\conda\conda\envs\pythondata\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
# limit to categorical data using df.select_dtypes()
y= X['Category'].ravel()
X = X.astype({'movie_sequel':'object'})

In [5]:
X = X.select_dtypes(include=[object])
X.head(3)

name  \
0                                         Avatar   
1  Harry Potter and the Deathly Hallows: Part II   
2                                 Transformers 3   

                                    display_name movie_sequel  \
0                                         Avatar            0   
1  Harry Potter and the Deathly Hallows: Part II            1   
2                 Transformers: Dark of the Moon            1   

     creative_type                             source      production_method  \
0  Science Fiction                Original Screenplay  Animation/Live Action   
1          Fantasy  Based on Fiction Book/Short Story  Animation/Live Action   
2  Science Fiction                        Based on TV  Animation/Live Action   

       genre language                                board_rating_reason  \
0     Action  English  For intense epic battle sequences and warfare,...   
1  Adventure  English  for some sequences of intense action violence ...   
2     Action  English  for intense prolonged sequences of sci-fi acti...   

  movie_board_rating_display_name movie_release_pattern_display_name  
0                           PG-13                               Wide  
1                           PG-13                               Wide  
2                           PG-13                               Wide

In [6]:
# check original shape
X.shape

(1196, 11)

In [7]:
# view columns using df.columns
X.columns
Decoder ={}

In [8]:
# TODO: create a LabelEncoder object and fit it to each feature in X
# import preprocessing from sklearn
from sklearn import preprocessing
X_2 =X

# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
for col in X.columns:
    le = preprocessing.LabelEncoder()
    le.fit(X[col])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(le_name_mapping)
    Decoder[col]=le_name_mapping
# # 2/3. FIT AND TRANSFORM
# # use df.apply() to apply le.fit_transform to all columns
# X_2 = X.apply(le.fit(X['Vehicle Style']))
# X_2.head()

    X_2[col]=le.transform(X[col])
X_2.head()

{'10,000 B.C.': 0, '12 Rounds': 1, '127 Hours': 2, '1408': 3, '2010 Oscar Shorts': 4, '2011 Oscar Shorts': 5, '2012': 6, '2012 Oscar Shorts': 7, '21': 8, '21 Jump Street': 9, '27 Dresses': 10, '28 Weeks Later': 11, '3 Idiots': 12, '30 Days of Night': 13, '30 Minutes or Less': 14, '300': 15, '3:10 to Yuma': 16, '4 luni, 3 saptamani si 2 zile': 17, '500 Days of Summer': 18, '5050': 19, '5150, Rue des Ormes': 20, '88 Minutes': 21, '9': 22, 'A-Team, The': 23, 'Abandoned, The': 24, 'Abduction': 25, 'Abraham Lincoln Vampire Hunter': 26, 'Abrazos rotos, Los': 27, 'Across the Universe': 28, 'Adam': 29, 'Adjustment Bureau, The': 30, 'Adventureland': 31, 'Adventures of Tintin: Secret of the Unicorn': 32, 'African Cats': 33, 'Age des Tenebres, L': 34, 'Albert Nobbs': 35, 'Alfred Hitchcock and the Making of Psycho': 36, 'Alice in Wonderland (2010)': 37, 'Aliens in the Attic': 38, 'Aliens vs. Predator: Requiem': 39, 'All About Steve': 40, 'Alpha Dog': 41, 'Alpha and Omega': 42, 'Alvin and the Chipm

name  display_name  movie_sequel  creative_type  source  production_method  \
0    74            75             0              7      13                  0   
1   457           383             1              3       2                  0   
2  1076          1104             1              7       9                  0   
3  1072          1099             1              5      13                  1   
4   827           686             1              3      10                  3   

   genre  language  board_rating_reason  movie_board_rating_display_name  \
0      0         2                   17                                4   
1      1         2                  683                                4   
2      0         2                  274                                4   
3      1         2                  111                                0   
4      1         2                  284                                4   

   movie_release_pattern_display_name  
0                                   6  
1                                   6  
2                                   6  
3                                   6  
4                                   6

In [9]:
sum=0
for item in Decoder:
    print(Decoder[item])
    sum=sum+len(Decoder[item])
print(sum)

{'10,000 B.C.': 0, '12 Rounds': 1, '127 Hours': 2, '1408': 3, '2010 Oscar Shorts': 4, '2011 Oscar Shorts': 5, '2012': 6, '2012 Oscar Shorts': 7, '21': 8, '21 Jump Street': 9, '27 Dresses': 10, '28 Weeks Later': 11, '3 Idiots': 12, '30 Days of Night': 13, '30 Minutes or Less': 14, '300': 15, '3:10 to Yuma': 16, '4 luni, 3 saptamani si 2 zile': 17, '500 Days of Summer': 18, '5050': 19, '5150, Rue des Ormes': 20, '88 Minutes': 21, '9': 22, 'A-Team, The': 23, 'Abandoned, The': 24, 'Abduction': 25, 'Abraham Lincoln Vampire Hunter': 26, 'Abrazos rotos, Los': 27, 'Across the Universe': 28, 'Adam': 29, 'Adjustment Bureau, The': 30, 'Adventureland': 31, 'Adventures of Tintin: Secret of the Unicorn': 32, 'African Cats': 33, 'Age des Tenebres, L': 34, 'Albert Nobbs': 35, 'Alfred Hitchcock and the Making of Psycho': 36, 'Alice in Wonderland (2010)': 37, 'Aliens in the Attic': 38, 'Aliens vs. Predator: Requiem': 39, 'All About Steve': 40, 'Alpha Dog': 41, 'Alpha and Omega': 42, 'Alvin and the Chipm

In [10]:
X_2.head()

name  display_name  movie_sequel  creative_type  source  production_method  \
0    74            75             0              7      13                  0   
1   457           383             1              3       2                  0   
2  1076          1104             1              7       9                  0   
3  1072          1099             1              5      13                  1   
4   827           686             1              3      10                  3   

   genre  language  board_rating_reason  movie_board_rating_display_name  \
0      0         2                   17                                4   
1      1         2                  683                                4   
2      0         2                  274                                4   
3      1         2                  111                                0   
4      1         2                  284                                4   

   movie_release_pattern_display_name  
0                                   6  
1                                   6  
2                                   6  
3                                   6  
4                                   6

In [11]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical


y= y.ravel()
X_train, X_test, y_train, y_test = train_test_split(
    X_2, y, random_state=42, stratify=y)

X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)

encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)


# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
print(y_test_categorical)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [12]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(11,), random_state=1)

clf.fit(X_train_scaled, encoded_y_train)                         
MLPClassifier(activation='softmax', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(9,),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

MLPClassifier(activation='softmax', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(9,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [13]:
# # dropout in the input layer with weight constraint
# def create_model():
# 	# create model
# 	model = Sequential()
# 	model.add(Dropout(0.3, input_shape=(11,)))
# 	model.add(Dense(60, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))
# 	model.add(Dense(30, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))
# 	model.add(Dense(1, kernel_initializer='normal', activation='softmax'))
# 	# Compile model
# 	sgd = SGD(lr=0.1, momentum=0.99, decay=0.0, nesterov=False)
# 	model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
# 	return model

# np.random.seed(seed)
# estimators = []
# # estimators.append(('standardize', StandardScaler()))
# estimators.append(('mlp', KerasClassifier(build_fn=create_model, epochs=300, batch_size=16, verbose=0)))
# pipeline = Pipeline(estimators)
# kfold = StratifiedKFold(n_splits=6, shuffle=True, random_state=seed)
# results = cross_val_score(pipeline, X_train_scaled, encoded_y_train, cv=kfold)
# print("Visible: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [14]:
# from keras.models import Sequential
# from keras.layers import Dense

# # dropout in hidden layers with weight constraint
# def create_model():
# 	# create model
# 	model = Sequential()
# 	model.add(Dense(60, input_dim=11, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))
# 	model.add(Dropout(0.2))
# 	model.add(Dense(30, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))
# 	model.add(Dropout(0.2))
# 	model.add(Dense(1, kernel_initializer='normal', activation='softmax'))
# 	# Compile model
# 	sgd = SGD(lr=0.1, momentum=0.9, decay=0.0, nesterov=False)
# 	model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
# 	return model

# np.random.seed(seed)
# estimators = []
# estimators.append(('standardize', StandardScaler()))
# estimators.append(('mlp', KerasClassifier(build_fn=create_model, epochs=300, batch_size=16, verbose=0)))
# pipeline = Pipeline(estimators)
# kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
# results = cross_val_score(pipeline, X_train_scaled, encoded_y_train, cv=kfold)
# print("Hidden: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [15]:
# Make predictions with the hypertuned model
predictions = clf.predict(X_test_scaled)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(encoded_y_test,predictions))

[[26  9  5  1  0  0  0  1  0]
 [19 19 10  9  3  0  1  1  0]
 [10 10 17 17  2  2  1  2  0]
 [ 6  3 17 13  4  0  2  5  1]
 [ 1  0 10 12  3  0  4  3  0]
 [ 1  2  2  5  3  1  2  2  2]
 [ 1  1  1  3  0  0  6  2  1]
 [ 1  0  0  3  1  0  0  2  3]
 [ 0  0  0  0  0  0  1  0  4]]


In [17]:
print(classification_report(encoded_y_test,predictions))

             precision    recall  f1-score   support

          0       0.40      0.62      0.49        42
          1       0.43      0.31      0.36        62
          2       0.27      0.28      0.28        61
          3       0.21      0.25      0.23        51
          4       0.19      0.09      0.12        33
          5       0.33      0.05      0.09        20
          6       0.35      0.40      0.38        15
          7       0.11      0.20      0.14        10
          8       0.36      0.80      0.50         5

avg / total       0.31      0.30      0.29       299



In [18]:
from sklearn.metrics import r2_score
print('Variance score: %.2f' % r2_score(encoded_y_test, predictions))

Variance score: 0.08


In [19]:
neural_classification = predictions
neural_labels=[]
j=0
for i in neural_classification:
    neural_labels.append([i,y_test[j]])
    j+=1
neural_labels
testdf=pd.DataFrame(neural_labels)

testdf=testdf.rename(columns={0: 'Class', 1: 'Category'})
# testdf['Category'].any()
testdf=testdf.sort_values('Class', ascending=True)
testdf=testdf.set_index("Class")

In [20]:
classes_movies = clf.classes_
# labels = classifier.labels_
print(classes_movies)

[0 1 2 3 4 5 6 7 8]


In [21]:
testdf.to_csv("Training_Neural_prediction.csv")

In [22]:
test=X_2[:1]

test

name  display_name  movie_sequel  creative_type  source  production_method  \
0    74            75             0              7      13                  0   

   genre  language  board_rating_reason  movie_board_rating_display_name  \
0      0         2                   17                                4   

   movie_release_pattern_display_name  
0                                   6

In [23]:
clf.predict(test)

array([4], dtype=int64)

In [24]:
clf.score(X_2, y, sample_weight=None)

0.1688963210702341

In [25]:
import pickle
filename = 'neural_labelencoded_movies.sav'
pickle.dump(clf, open(filename, 'wb'))

In [26]:
scoring = pd.read_csv("Scoring Sheet.csv")
scoring.head()

id                                    name  \
0    7970115                    Avengers, The (2011)   
1  174540115                   Dark Knight Rises The   
2  149080115                                 Bond 23   
3  136020115  Twilight Saga Breaking Dawn Part 2 The   
4   53500115                             Hobbit, The   

                               display_name  production_budget  \
0                     Marvel's The Avengers          225000000   
1                     The Dark Knight Rises                  0   
2                                   Skyfall          200000000   
3  The Twilight Saga: Breaking Dawn, Part 2          136200000   
4         The Hobbit: An Unexpected Journey          270000000   

   production_year  movie_sequel         creative_type  \
0             2012             0            Super Hero   
1             2012             1            Super Hero   
2             2012             1  Contemporary Fiction   
3             2012             1               Fantasy   
4             2012             1               Fantasy   

                              source      production_method      genre  \
0       Based on Comic/Graphic Novel            Live Action  Adventure   
1       Based on Comic/Graphic Novel            Live Action     Action   
2  Based on Fiction Book/Short Story            Live Action     Action   
3  Based on Fiction Book/Short Story            Live Action      Drama   
4  Based on Fiction Book/Short Story  Animation/Live Action  Adventure   

  language                                board_rating_reason  \
0  English  for intense sequences of sci-fi violence and a...   
1  English  for intense sequences of violence and action, ...   
2  English  for intense violent sequences throughout, some...   
3  English  for sequences of violence including disturbing...   
4  English  for extended sequences of intense fantasy acti...   

  movie_board_rating_display_name movie_release_pattern_display_name  
0                           PG-13                               Wide  
1                           PG-13                               Wide  
2                           PG-13                               Wide  
3                           PG-13                               Wide  
4                           PG-13                               Wide

In [27]:
# limit to categorical data using df.select_dtypes()
# y= X['Category'].ravel()
scoring = scoring.astype({'movie_sequel':'object'})
X_p = scoring.select_dtypes(include=[object])
X_p.head(3)

name           display_name movie_sequel  \
0   Avengers, The (2011)  Marvel's The Avengers            0   
1  Dark Knight Rises The  The Dark Knight Rises            1   
2                Bond 23                Skyfall            1   

          creative_type                             source production_method  \
0            Super Hero       Based on Comic/Graphic Novel       Live Action   
1            Super Hero       Based on Comic/Graphic Novel       Live Action   
2  Contemporary Fiction  Based on Fiction Book/Short Story       Live Action   

       genre language                                board_rating_reason  \
0  Adventure  English  for intense sequences of sci-fi violence and a...   
1     Action  English  for intense sequences of violence and action, ...   
2     Action  English  for intense violent sequences throughout, some...   

  movie_board_rating_display_name movie_release_pattern_display_name  
0                           PG-13                               Wide  
1                           PG-13                               Wide  
2                           PG-13                               Wide

In [28]:
# check original shape
X_p.shape

(91, 11)

In [29]:
# view columns using df.columns
X_p.columns
Decoder_p ={}

In [30]:
# TODO: create a LabelEncoder object and fit it to each feature in X
# import preprocessing from sklearn
from sklearn import preprocessing
X_p2 =X_p

# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
for col in X_p.columns:
    le = preprocessing.LabelEncoder()
    le.fit(X_p[col])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(le_name_mapping)
    Decoder_p[col]=le_name_mapping
# # 2/3. FIT AND TRANSFORM
# # use df.apply() to apply le.fit_transform to all columns
# X_2 = X.apply(le.fit(X['Vehicle Style']))
# X_2.head()

    X_p2[col]=le.transform(X_p[col])
X_p2.head()

{'2016': 0, 'Act of Valor': 1, 'Agneepath': 2, 'Air Racers 3D': 3, 'Alex Cross': 4, 'American Reunion': 5, 'Anna Karenina (2012)': 6, 'Arbitrage': 7, 'Argo': 8, 'Atlas Shrugged Part II': 9, 'Avengers, The (2011)': 10, 'Barfi': 11, 'Beasts of the Southern Wild': 12, 'Best Exotic Marigold Hotel The': 13, 'Bol Bachchan': 14, 'Bond 23': 15, 'Brave': 16, 'Cirque du Soleil Worlds Away': 17, 'Clash of the Titans 2': 18, 'Cocktail (2012)': 19, 'Collection The': 20, 'Crooked Arrows': 21, 'Dabangg 2': 22, 'Dark Knight Rises The': 23, 'Diary of a Wimpy Kid Dog Days': 24, 'Ek Tha Tiger': 25, 'End of Watch': 26, 'English Vinglish': 27, 'Expendables II The': 28, 'Flight': 29, 'For Greater Glory': 30, 'For a Good Time Call': 31, 'Fun Size': 32, 'Gone': 33, 'Guardians, The': 34, 'Hit and Run (2012)': 35, 'Hobbit, The': 36, 'Housefull 2': 37, 'Hyde Park on the Hudson': 38, 'Ice Age Continental Drift': 39, 'Jab Tak Hai Jaan': 40, 'Jack Reacher': 41, 'Journey 2 Mysterious Island': 42, 'Katy Perry Part of

C:\Users\dinot\AppData\Local\conda\conda\envs\pythondata\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


{'Based on Comic/Graphic Novel': 0, 'Based on Factual Book/Article': 1, 'Based on Fiction Book/Short Story': 2, 'Based on Folk Tale/Legend/Fairytale': 3, 'Based on Game': 4, 'Based on Play': 5, 'Based on Real Life Events': 6, 'Based on TV': 7, 'Original Screenplay': 8, 'Remake': 9}
{'Animation/Live Action': 0, 'Digital Animation': 1, 'Live Action': 2}
{'Action': 0, 'Adventure': 1, 'Comedy': 2, 'Concert/Performance': 3, 'Documentary': 4, 'Drama': 5, 'Horror': 6, 'Romantic Comedy': 7, 'Thriller/Suspense': 8}
{'English': 0, 'French': 1, 'Hindi': 2, 'Indonesian/Balinese': 3, 'Spanish': 4}
{'General': 0, 'International - to be excluded': 1, 'for a scene of violence, brief language and drug use.': 2, 'for bloody violence and grisly images.': 3, 'for brief graphic nudity and language.': 4, 'for brief language.': 5, 'for brief sexuality.': 6, 'for brief strong language and smoking.': 7, 'for crude and sexual content throughout, nudity, language, brief drug use and teen drinking.': 8, 'for crud

name  display_name  movie_sequel  creative_type  source  production_method  \
0    10            44             0              7       0                  2   
1    23            69             1              7       0                  2   
2    15            62             1              0       2                  2   
3    83            78             1              3       2                  2   
4    36            71             1              3       2                  0   

   genre  language  board_rating_reason  movie_board_rating_display_name  \
0      1         0                   17                                3   
1      0         0                   19                                3   
2      0         0                   20                                3   
3      5         0                   36                                3   
4      1         0                   15                                3   

   movie_release_pattern_display_name  
0                                   5  
1                                   5  
2                                   5  
3                                   5  
4                                   5

In [31]:
sum_p=0
for item in Decoder_p:
    print(Decoder_p[item])
    sum_p=sum_p+len(Decoder_p[item])
print(sum_p)

{'2016': 0, 'Act of Valor': 1, 'Agneepath': 2, 'Air Racers 3D': 3, 'Alex Cross': 4, 'American Reunion': 5, 'Anna Karenina (2012)': 6, 'Arbitrage': 7, 'Argo': 8, 'Atlas Shrugged Part II': 9, 'Avengers, The (2011)': 10, 'Barfi': 11, 'Beasts of the Southern Wild': 12, 'Best Exotic Marigold Hotel The': 13, 'Bol Bachchan': 14, 'Bond 23': 15, 'Brave': 16, 'Cirque du Soleil Worlds Away': 17, 'Clash of the Titans 2': 18, 'Cocktail (2012)': 19, 'Collection The': 20, 'Crooked Arrows': 21, 'Dabangg 2': 22, 'Dark Knight Rises The': 23, 'Diary of a Wimpy Kid Dog Days': 24, 'Ek Tha Tiger': 25, 'End of Watch': 26, 'English Vinglish': 27, 'Expendables II The': 28, 'Flight': 29, 'For Greater Glory': 30, 'For a Good Time Call': 31, 'Fun Size': 32, 'Gone': 33, 'Guardians, The': 34, 'Hit and Run (2012)': 35, 'Hobbit, The': 36, 'Housefull 2': 37, 'Hyde Park on the Hudson': 38, 'Ice Age Continental Drift': 39, 'Jab Tak Hai Jaan': 40, 'Jack Reacher': 41, 'Journey 2 Mysterious Island': 42, 'Katy Perry Part of

In [32]:
X_p2.head()

name  display_name  movie_sequel  creative_type  source  production_method  \
0    10            44             0              7       0                  2   
1    23            69             1              7       0                  2   
2    15            62             1              0       2                  2   
3    83            78             1              3       2                  2   
4    36            71             1              3       2                  0   

   genre  language  board_rating_reason  movie_board_rating_display_name  \
0      1         0                   17                                3   
1      0         0                   19                                3   
2      0         0                   20                                3   
3      5         0                   36                                3   
4      1         0                   15                                3   

   movie_release_pattern_display_name  
0                                   5  
1                                   5  
2                                   5  
3                                   5  
4                                   5

In [33]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_p2)
print("The test data belongs to Class: ", result)
df=X_p2.loc[X_p2.index==result[0]]

The test data belongs to Class:  [6 6 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 4 4 6 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 5 4 4 4 4 4 4 4 4 4 4 4]


In [34]:
len(result)

91

In [35]:
scoring['Category_neural']= result

In [36]:
scoring.head()

id                                    name  \
0    7970115                    Avengers, The (2011)   
1  174540115                   Dark Knight Rises The   
2  149080115                                 Bond 23   
3  136020115  Twilight Saga Breaking Dawn Part 2 The   
4   53500115                             Hobbit, The   

                               display_name  production_budget  \
0                     Marvel's The Avengers          225000000   
1                     The Dark Knight Rises                  0   
2                                   Skyfall          200000000   
3  The Twilight Saga: Breaking Dawn, Part 2          136200000   
4         The Hobbit: An Unexpected Journey          270000000   

   production_year movie_sequel         creative_type  \
0             2012            0            Super Hero   
1             2012            1            Super Hero   
2             2012            1  Contemporary Fiction   
3             2012            1               Fantasy   
4             2012            1               Fantasy   

                              source      production_method      genre  \
0       Based on Comic/Graphic Novel            Live Action  Adventure   
1       Based on Comic/Graphic Novel            Live Action     Action   
2  Based on Fiction Book/Short Story            Live Action     Action   
3  Based on Fiction Book/Short Story            Live Action      Drama   
4  Based on Fiction Book/Short Story  Animation/Live Action  Adventure   

  language                                board_rating_reason  \
0  English  for intense sequences of sci-fi violence and a...   
1  English  for intense sequences of violence and action, ...   
2  English  for intense violent sequences throughout, some...   
3  English  for sequences of violence including disturbing...   
4  English  for extended sequences of intense fantasy acti...   

  movie_board_rating_display_name movie_release_pattern_display_name  \
0                           PG-13                               Wide   
1                           PG-13                               Wide   
2                           PG-13                               Wide   
3                           PG-13                               Wide   
4                           PG-13                               Wide   

   Category_neural  
0                6  
1                6  
2                6  
3                4  
4                4

In [37]:
scoring.to_csv('Scoring_sheet_neural.csv')